version: "3.9"
services:
  homeassistant:
    image: "ghcr.io/home-assistant/home-assistant:stable"
    ports:
      - 10.55.8.3:8123:8123
    volumes:
      - /home/willem/homeassistant:/config
      - /home/willem/repos/homeAutomation/home-assistant/configuration.yaml:/config/configuration.yaml
    restart: unless-stopped
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /home/willem/syncthing:/data1
    ports:
      - 10.55.8.3:8384:8384
      - 10.55.8.3:22000:22000/tcp
      - 10.55.8.3:22000:22000/udp
      - 10.55.8.3:21027:21027/udp
    restart: unless-stopped
