version: "3.9"
services:
  db:
    image: mariadb
    restart: unless-stopped
    ports:
      - ${INTERNAL_IP}:3306:3306
    env_file:
      # Override the mariadb-specific settings in a .env.mariadb file.
      # You should create the .env.mariadb file yourself.
      - .env
      - .env.mariadb
  homeassistant:
    image: "ghcr.io/home-assistant/home-assistant:stable"
    ports:
      - ${INTERNAL_IP}:8123:8123
    volumes:
      - /home/willem/homeassistant:/config
      - /home/willem/repos/homeAutomation/configurations/home-assistant/configuration.yaml:/config/configuration.yaml
    restart: unless-stopped
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /home/willem/syncthing:/data1
    ports:
      - ${INTERNAL_IP}:8384:8384
      - ${INTERNAL_IP}:22000:22000/tcp
      - ${INTERNAL_IP}:22000:22000/udp
      - ${INTERNAL_IP}:21027:21027/udp
    restart: unless-stopped
