version: "3.9"
services:
  whoami:
    restart: unless-stopped
    network_mode: "host"
    image: traefik/whoami
    command:
      - --port=2001
  traefik:
    restart: unless-stopped
    network_mode: "host"
    image: "traefik:1.7.10"
    volumes:
      - /home/pi/repos/homeAutomation/configurations/traefik/traefik.1.7.10.toml:/etc/traefik/traefik.toml
  mosquitto:
    restart: unless-stopped
    image: eclipse-mosquitto:2
    volumes:
      - /home/pi/repos/homeAutomation/configurations/eclipse-mosquitto/:/mosquitto/config/:ro
      - ./log/:/mosquitto/log/
    ports:
      - 2883:1883
      - 9001:9001
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - 9100:9100
