defaultEntryPoints = ["http"]

[entryPoints]
    [entryPoints.whoami]
    address = ":8088"
    [entryPoints.homeassistant]
    address = ":8089"
    [entryPoints.syncthing]
    address = ":8090"
    [entryPoints.grafana]
    address = ":8091"

[file]

[backends]
    [backends.whoami]
        [backends.whoami.servers.server1]
        url = "http://localhost:2001"
    [backends.homeassistant]
        [backends.homeassistant.servers.server1]
        url = "http://10.55.8.3:8123/"
    [backends.syncthing]
        [backends.syncthing.servers.server1]
        url = "http://10.55.8.3:8384/"
    [backends.grafana]
        [backends.grafana.servers.server1]
        url = "http://10.55.8.3:3000/"

[frontends]
    [frontends.whoami]
    entryPoints = ["whoami"]
    backend = "whoami"

    [frontends.homeassistant]
    entryPoints = ["homeassistant"]
    backend = "homeassistant"

    [frontends.syncthing]
    entryPoints = ["syncthing"]
    backend = "syncthing"

    [frontends.grafana]
    entryPoints = ["grafana"]
    backend = "grafana"
    passHostHeader = true
