[entryPoints]
  [entryPoints.http]
  address = ":80"

  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]
		  [[entryPoints.https.tls.certificates]]
		  certFile = "/var/lib/certificates/cert.pem"
		  keyFile = "/var/lib/certificates/key.pem"

[file]
[backends]
    [backends.whoami]
        [backends.whoami.servers.server1]
        url = "http://whoami:2001"

    [backends.grafana]
        [backends.grafana.servers.server1]
        url = "http://grafana:3000"

    [backends.syncthing]
        [backends.syncthing.servers.server1]
        url = "http://syncthing:8384"

    [backends.homeassistant]
        [backends.homeassistant.servers.server1]
        url = "http://homeassistant:8123"

    [backends.influxdb]
        [backends.influxdb.servers.server1]
        url = "http://influxdb:8086"

[frontends]
		  [frontends.whoami]
		  backend = "whoami"
		      [frontends.whoami.routes.path]
				rule = "Path:/whoami;ReplacePathRegex: ^/whoami(.*) /$1"

		  [frontends.grafana]
		  backend = "grafana"
		      [frontends.grafana.routes.path]
				rule = "Path:/grafana;ReplacePathRegex: ^/grafana(.*) /$1"

		  [frontends.syncthing]
		  backend = "syncthing"
		      [frontends.syncthing.routes.path]
				rule = "Path:/syncthing;ReplacePathRegex: ^/syncthing(.*) /$1"

		  [frontends.syncthing-referrer]
		  backend = "syncthing"
		      [frontends.syncthing-referrer.routes.referrer]
				rule = "HeadersRegexp: Referer, /*.syncthing"

		  [frontends.homeassistant]
		  backend = "homeassistant"
		      [frontends.homeassistant.routes.path]
				rule = "Path:/homeassistant;ReplacePathRegex: ^/homeassistant(.*) /$1"

		  [frontends.influxdb]
		  backend = "influxdb"
		      [frontends.influxdb.routes.path]
				rule = "Path:/influxdb;ReplacePathRegex: ^/influxdb(.*) /$1"

		  [frontends.influxdb-referrer]
		  backend = "influxdb"
		      [frontends.influxdb-referrer.routes.referrer]
				rule = "HeadersRegexp: Referer, /*.influxdb"


[tracing]
  [tracing.otlp.http]
    endpoint = "http://otel-collector:4318"
	 insecure = true
