apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  selector:
    matchLabels:
      app: rabbitmq
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: registry.willemserruys.com/rabbitmq
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 1883
            - containerPort: 15672
      imagePullSecrets:
      - name: regcred