apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  type: NodePort
  ports:
  - port: 1883
    name: mqtt
    targetPort: 1883
    nodePort: {{ .Values.rabbitmq.mqtt_nodePort }}
    protocol: TCP
  - port: 15672
    name: portal
    targetPort: 15672
    nodePort: {{ .Values.rabbitmq.portal_nodePort }}
    protocol: TCP
  selector:
    app: rabbitmq
