defaultEntryPoints = ["http"]

[entryPoints]
    [entryPoints.whoami]
    address = ":8088"
    [entryPoints.homeassistant]
    address = ":8089"
    [entryPoints.syncthing]
    address = ":8090"
    [entryPoints.rabbitmq-admin]
    address = ":8091"
    [entryPoints.rabbitmq]
    address = ":8092"

[file]

[backends]
    [backends.whoami]
        [backends.whoami.servers.server1]
        url = "http://localhost:2001"
    [backends.homeassistant]
        [backends.homeassistant.servers.server1]
        url = "http://10.55.8.3:8123/"
    [backends.syncthing]
        [backends.syncthing.servers.server1]
        url = "http://10.55.8.3:8384/"
    [backends.rabbitmq-admin]
        [backends.rabbitmq-admin.servers.server1]
        url = "http://10.55.8.3:15672/"
    [backends.rabbitmq]
        [backends.rabbitmq.servers.server1]
        url = "http://10.55.8.3:1883/"

[frontends]
    [frontends.whoami]
    entryPoints = ["whoami"]
    backend = "whoami"

    [frontends.homeassistant]
    entryPoints = ["homeassistant"]
    backend = "homeassistant"

    [frontends.syncthing]
    entryPoints = ["syncthing"]
    backend = "syncthing"

    [frontends.rabbitmq-admin]
    entryPoints = ["rabbitmq-admin"]
    backend = "rabbitmq-admin"

    [frontends.rabbitmq]
    entryPoints = ["rabbitmq"]
    backend = "rabbitmq"

