version: "3.9"
services:
  rabbitmq:
    image: "registry.willemserruys.com/rabbitmq:latest"
    ports:
      - 2883:1883
      - 15672:15672
  homeassistant:
    image: "ghcr.io/home-assistant/home-assistant:stable"
    ports:
      - 8123:8123
    volumes:
      - /home/willem/homeassistant:/config