{
 "title": "Energy Consumption",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Energy Consumption",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 23, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"homeassistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"W\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"domain\"] == \"sensor\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"p1_meter_power\" or r[\"entity_id\"] == \"p1_meter_power_phase_1\" or r[\"entity_id\"] == \"p1_meter_power_phase_2\" or r[\"entity_id\"] == \"p1_meter_power_phase_3\")\r\n    |> group(columns: [\"friendly_name\"], mode: \"by\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  },
  {
   "title": "Heat Pump Consumption",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 23, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"homeassistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"friendly_name\"] == \"Heat Pump power\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n      |> group(columns: [\"friendly_name\"], mode: \"by\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  },
  {
   "title": "Christmas Lights",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 23, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "query": "from(bucket: \"homeassistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"shellyplusplugs_c82e18083448_switch_0\" or r[\"entity_id\"] == \"shellyplusplugs_fcb4670e63cc_switch_0\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n      |> group(columns: [\"entity_id\"], mode: \"by\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Carport Light",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 23, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "query": "from(bucket: \"homeassistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"shelly1_98cdac2de851\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n      |> group(columns: [\"friendly_name\"], mode: \"by\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}