apiVersion: v1
kind: Service
metadata:
  name: homeassistant
spec:
  type: NodePort
  ports:
  - port: 8123
    name: portal
    targetPort: 8123
    nodePort: {{ .Values.homeassistant.portal_nodePort }}
    protocol: TCP
  selector:
    app: homeassistant
