general:
# This should be the name of your PC
  hostname: willem-server

rabbitmq:
  mqtt_nodePort: 30001
  portal_nodePort: 30002

homeassistant:
  portal_nodePort: 30003
  config_folder: /home/willem/homeassistant/config